/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moklet
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        et2 = new javax.swing.JTextField();
        et1 = new javax.swing.JTextField();
        bKurang = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bBagi = new javax.swing.JButton();
        bKali = new javax.swing.JButton();
        etHasil = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kalkulator seederhana");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 170, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Bilangan 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 60, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Bilangan 1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 70, 60, 15);

        et2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et2ActionPerformed(evt);
            }
        });
        getContentPane().add(et2);
        et2.setBounds(130, 110, 80, 30);

        et1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et1ActionPerformed(evt);
            }
        });
        getContentPane().add(et1);
        et1.setBounds(130, 60, 80, 30);

        bKurang.setText("-");
        bKurang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKurangActionPerformed(evt);
            }
        });
        getContentPane().add(bKurang);
        bKurang.setBounds(70, 150, 40, 30);

        bTambah.setText("+");
        bTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        getContentPane().add(bTambah);
        bTambah.setBounds(20, 150, 40, 30);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        bBagi.setText("/");
        bBagi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBagiActionPerformed(evt);
            }
        });
        jPanel1.add(bBagi);
        bBagi.setBounds(180, 150, 37, 30);

        bKali.setText("X");
        bKali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKaliActionPerformed(evt);
            }
        });
        jPanel1.add(bKali);
        bKali.setBounds(130, 150, 39, 30);

        etHasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etHasil.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        etHasil.setFocusable(false);
        jPanel1.add(etHasil);
        etHasil.setBounds(80, 220, 90, 30);

        jButton1.setText("CLOSE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 260, 90, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HASIL");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 180, 70, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 290);

        setSize(new java.awt.Dimension(265, 327));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void et2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et2ActionPerformed

    private void et1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et1ActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        double satu = Integer.parseInt(et1.getText());
        double dua = Integer.parseInt(et2.getText());
        
        double hasilplus = satu + dua;
        
        etHasil.setText(String.valueOf(hasilplus));
        // TODO add your handling code here:
    }//GEN-LAST:event_bTambahActionPerformed

    private void bKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKurangActionPerformed
        double satu = Integer.parseInt(et1.getText());
        double dua = Integer.parseInt(et2.getText());
        
        double hasilplus = satu - dua;
        
        etHasil.setText(String.valueOf(hasilplus));
        // TODO add your handling code here:
    }//GEN-LAST:event_bKurangActionPerformed

    private void bKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKaliActionPerformed
        double satu = Integer.parseInt(et1.getText());
        double dua = Integer.parseInt(et2.getText());
        
        double hasilplus = satu * dua;
        
        etHasil.setText(String.valueOf(hasilplus));
        // TODO add your handling code here:
    }//GEN-LAST:event_bKaliActionPerformed

    private void bBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBagiActionPerformed
        double satu = Integer.parseInt(et1.getText());
        double dua = Integer.parseInt(et2.getText());
        
        double hasilplus = satu / dua;
        
        etHasil.setText(String.valueOf(hasilplus));
        // TODO add your handling code here:
    }//GEN-LAST:event_bBagiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBagi;
    private javax.swing.JButton bKali;
    private javax.swing.JButton bKurang;
    private javax.swing.JButton bTambah;
    private javax.swing.JTextField et1;
    private javax.swing.JTextField et2;
    private javax.swing.JTextField etHasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
